CumulativePart3/CumulativePart2/CumulatievePart1/Controllers/CoursePageController.cs
//An MVC Controller to route to dynamic pages for courses.


using Microsoft.AspNetCore.Mvc;
using CumulatievePart1.Models;
using System.Linq;

namespace CumulatievePart1.Controllers
{
    public class CoursePageController : Controller
    {
        private readonly CourseAPIController _api;

        public CoursePageController(CourseAPIController api)
        {
            _api = api;
        }

        /// <summary>
        /// Displays a list of all courses.
        /// </summary>
        public IActionResult List()
        {
            List<Course> courses = _api.ListOfCourses();
            return View(courses); 
        // Pass the list of courses to the view
        }

        /// <summary>
        /// Displaying details of a selected course by ID .
        /// </summary>
        /// 
        public IActionResult Show(int id)
        {
            Course course = _api.FindCourseDetail(id);
            return View(course); 
        // Pass the course details to the view
        }

   [HttpGet]
        public IActionResult New(int id)
        {
            return View();
        }

        // POST: TeacherPage/Create
        [HttpPost]
        public IActionResult Create(Course NewCourse)
        {
            int CourseId = _api.AddCourse(NewCourse);

            // redirects to "Show" action on "Author" cotroller with id parameter supplied
            return RedirectToAction("Show", new {id = CourseId});
        }

        // GET : AuthorPage/DeleteConfirm/{id}
        [HttpGet]
        public IActionResult DeleteConfirm(int id)
        {
            Course SelectedCourse = _api.FindCourseDetail(id);
            return View(SelectedCourse);
        }

        // POST: AuthorPage/Delete/{id}
        [HttpPost]
        public IActionResult Delete(int id)
        {
            int CourseId = _api.DeleteCourse(id);
            // redirects to list action
            return RedirectToAction("List");
        }


        [HttpGet]
        public IActionResult Edit(int id)
        {
            
        // Fetch the course using the API
            Course SelectedCourse = _api.FindCourseDetail(id);
            return View(SelectedCourse);
        }

        [HttpPost]
        public IActionResult Update(int id, string CourseCode, int TeacherId, DateTime StartDate, DateTime FinishDate, string CourseName)
        {
            
            Course UpdatedCourse = new Course();

            UpdatedCourse.CourseCode = CourseCode;
            UpdatedCourse.TeacherId = TeacherId;
            UpdatedCourse.StartDate = StartDate;
            UpdatedCourse.FinishDate = FinishDate;
            UpdatedCourse.CourseName = CourseName;
            

        // Update the course using the API (assuming _api.UpdateCourse works similarly to the Teacher example)
            _api.UpdateCourse(id, UpdatedCourse);

        // Redirect to the 'Show' action to display the updated course
            return RedirectToAction("Show", new { id = id });
    }
}
}

CumulativePart3/CumulativePart2/CumulatievePart1/Controllers/StudentPageController.cs
//An MVC Controller to route to dynamic pages for students.


using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using CumulatievePart1.Models;


namespace CumulatievePart1.Controllers
{
    public class StudentPageController : Controller
    {
        private readonly StudentAPIController _api;

        public StudentPageController(StudentAPIController api)
        {
            _api = api;
        }

        /// <summary>
        /// Displays a list of all students.
        /// </summary>
        /// <example>
        /// GET : api/StudentPage/List->Gives the list of all Students in the Database.
        /// </example>
        public IActionResult List()
        {
            List<Student> students = _api.ListOfStudents();
            // Pass the list of students to the view.
            return View(students); 
        }

        /// <summary>
        /// Displays details of a selected student by ID.
        /// /// </summary>
        /// /// <example>
        /// GET :api/StudentPage/Show/{id}->Gives the information of the Student
        /// </example>

        public IActionResult Show(int id)
        {
            Student student = _api.FindStudentDetail(id);
            // Pass the student details to the view
            return View(student); 
        }
    
    [HttpGet]
        public IActionResult New(int id)
        {
            return View();
        }

        // POST: TeacherPage/Create
        [HttpPost]
        public IActionResult Create(Student NewStudent)
        {
            int StudentId = _api.AddStudent(NewStudent);

            // redirects to "Show" action on "Author" cotroller with id parameter supplied
            return RedirectToAction("Show", new {id = StudentId});
        }

        // GET : AuthorPage/DeleteConfirm/{id}
        [HttpGet]
        public IActionResult DeleteConfirm(int id)
        {
            Student SelectedStudent = _api.FindStudentDetail(id);
            return View(SelectedStudent);
        }

        // POST: AuthorPage/Delete/{id}
        [HttpPost]
        public IActionResult Delete(int id)
        {
            int StudentId = _api.DeleteStudent(id);
            // redirects to list action
            return RedirectToAction("List");
            }

        // GET method to show the current student's details before editing
        [HttpGet]
        public IActionResult Edit(int id)
        {
            // Find the selected student by ID
            Student SelectedStudent = _api.FindStudentDetail(id);
            return View(SelectedStudent);  // Pass the student data to the Edit view
        }

        // POST method to handle the updated student data
        [HttpPost]
        public IActionResult Update(int id, string StudentFName, string StudentLName, DateTime EnrollDate, string StudentNumber)
        {
            // Create a new Student object to store the updated values
            Student UpdatedStudent = new Student();
            UpdatedStudent.StudentFName = StudentFName;
            UpdatedStudent.StudentLName = StudentLName;
            UpdatedStudent.EnrolDate = EnrollDate;
            UpdatedStudent.StudentNumber = StudentNumber;

        // Call the API to update the student in the database
            _api.UpdateStudent(id, UpdatedStudent);

    // Redirect to the Show page to display the updated student details
            return RedirectToAction("Show", new { id = id });
        }
        }
    }

CumulativePart3/CumulativePart2/CumulatievePart1/Controllers/TeacherPageController.cs
// An MVC Controller to route to dynamic pages.

using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using CumulatievePart1.Models;
using MySql.Data.MySqlClient;
using System;

namespace CumulatievePart1.Controllers
{
    public class TeacherPageController : Controller
    {
        private readonly TeacherAPIController _api;

        public TeacherPageController(TeacherAPIController api)
        {
            _api = api;
        }

        /// <summary>
        /// While clicking on the Teachers button in the Navigation Bar, it returns the web page displaying all the teachers in the Database school.
        /// </summary>
        /// <returns>
        /// List of all the Teachers in the Database school .
        /// </returns>
        /// <example>
        /// GET : api/TeacherPage/List->Gives the list of all Teachers in the Database school.
        /// </example>
        /// 
        [HttpGet]
        public IActionResult List()
        {
            List<Teacher> teachers = _api.ListOfTeachers();
            return View(teachers);
        }

        /// <summary>
        /// When we Select one Teacher from the list, it is returns the web page displaying the information of the Selected Teacher from the database school.
        /// </summary>
        /// <returns>
        /// Information of the Teacher from the database school.
        /// </returns>
        /// <example>
        /// GET :api/TeacherPage/Show/{id}->Gives the information of the Teacher.
        /// </example>
        public IActionResult Show(int id)
        {
            Teacher teacherData = _api.FindTeacherDetail(id);
            return View(teacherData);
        }
        [HttpGet]
        public IActionResult New(int id)
        {
            return View();
        }

        // POST: TeacherPage/Create
        [HttpPost]
        public IActionResult Create(Teacher NewTeacher)
        {
            int TeacherId = _api.AddTeacher(NewTeacher);

            // redirects to "Show" action on "Author" cotroller with id parameter supplied
            return RedirectToAction("Show", new {id = TeacherId});
        }

        // GET : AuthorPage/DeleteConfirm/{id}
        [HttpGet]
        public IActionResult DeleteConfirm(int id)
        {
            Teacher SelectedTeacher = _api.FindTeacherDetail(id);
            return View(SelectedTeacher);
        }

        // POST: AuthorPage/Delete/{id}
        [HttpPost]
        public IActionResult Delete(int id)
        {
            int TeacherId = _api.DeleteTeacher(id);
            // redirects to list actions
            return RedirectToAction("List");
             }
        [HttpGet]
        public IActionResult Edit(int id)
        {
            Teacher SelectedTeacher = _api.FindTeacherDetail(id);
            return View(SelectedTeacher);
        }
        // POST action to update teacher details after form submission
        [HttpPost]
        public IActionResult Update(int id, string TeacherFName, string TeacherLName, DateTime TeacherHireDate, string EmployeeNumber, decimal TeacherSalary)
        {

                 // Create a new Teacher object to hold the updated details  
            Teacher UpdatedTeacher = new Teacher();

 // Assign the incoming form data to the new Teacher object
            UpdatedTeacher.TeacherFName = TeacherFName;
            UpdatedTeacher.TeacherLName = TeacherLName;
            UpdatedTeacher.TeacherHireDate = TeacherHireDate;
            UpdatedTeacher.EmployeeNumber = EmployeeNumber;
            UpdatedTeacher.TeacherSalary = TeacherSalary;

    // Call the API method to update the teacher's data in the system
                _api.UpdateTeacher(id, UpdatedTeacher);

    // Redirect to the "Show" action to view the updated teacher details
                return RedirectToAction("Show", new { id = id });
        }

    }
}

CumulativePart3/CumulativePart2/CumulatievePart1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CumulativePart1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CumulatievePart1.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CumulativePart1</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                       <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Swagger" asp-action="Index">API</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TeacherPage" asp-action="List">Teachers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="StudentPage" asp-action="List">Students</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CoursePage" asp-action="List">Courses</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - CumulatievePart1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>